/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodosImport } from './routes/todos'
import { Route as LoginImport } from './routes/login'
import { Route as WebsiteImport } from './routes/_website'
import { Route as PlatformImport } from './routes/_platform'
import { Route as AuthImport } from './routes/_auth'
import { Route as WebsiteIndexImport } from './routes/_website/index'
import { Route as PlatformSettingsImport } from './routes/_platform/settings'
import { Route as PlatformJobsImport } from './routes/_platform/jobs'
import { Route as PlatformDashboardImport } from './routes/_platform/dashboard'
import { Route as PlatformCandidatesImport } from './routes/_platform/candidates'
import { Route as AuthSignUpImport } from './routes/_auth/sign-up'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'
import { Route as PlatformJobsJobIdImport } from './routes/_platform/jobs.$jobId'

// Create/Update Routes

const TodosRoute = TodosImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const WebsiteRoute = WebsiteImport.update({
  id: '/_website',
  getParentRoute: () => rootRoute,
} as any)

const PlatformRoute = PlatformImport.update({
  id: '/_platform',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const WebsiteIndexRoute = WebsiteIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRoute,
} as any)

const PlatformSettingsRoute = PlatformSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)

const PlatformJobsRoute = PlatformJobsImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => PlatformRoute,
} as any)

const PlatformDashboardRoute = PlatformDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlatformRoute,
} as any)

const PlatformCandidatesRoute = PlatformCandidatesImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => PlatformRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const PlatformJobsJobIdRoute = PlatformJobsJobIdImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => PlatformJobsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PlatformImport
      parentRoute: typeof rootRoute
    }
    '/_website': {
      id: '/_website'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WebsiteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthImport
    }
    '/_platform/candidates': {
      id: '/_platform/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof PlatformCandidatesImport
      parentRoute: typeof PlatformImport
    }
    '/_platform/dashboard': {
      id: '/_platform/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PlatformDashboardImport
      parentRoute: typeof PlatformImport
    }
    '/_platform/jobs': {
      id: '/_platform/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof PlatformJobsImport
      parentRoute: typeof PlatformImport
    }
    '/_platform/settings': {
      id: '/_platform/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PlatformSettingsImport
      parentRoute: typeof PlatformImport
    }
    '/_website/': {
      id: '/_website/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebsiteIndexImport
      parentRoute: typeof WebsiteImport
    }
    '/_platform/jobs/$jobId': {
      id: '/_platform/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof PlatformJobsJobIdImport
      parentRoute: typeof PlatformJobsImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PlatformJobsRouteChildren {
  PlatformJobsJobIdRoute: typeof PlatformJobsJobIdRoute
}

const PlatformJobsRouteChildren: PlatformJobsRouteChildren = {
  PlatformJobsJobIdRoute: PlatformJobsJobIdRoute,
}

const PlatformJobsRouteWithChildren = PlatformJobsRoute._addFileChildren(
  PlatformJobsRouteChildren,
)

interface PlatformRouteChildren {
  PlatformCandidatesRoute: typeof PlatformCandidatesRoute
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformJobsRoute: typeof PlatformJobsRouteWithChildren
  PlatformSettingsRoute: typeof PlatformSettingsRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformCandidatesRoute: PlatformCandidatesRoute,
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformJobsRoute: PlatformJobsRouteWithChildren,
  PlatformSettingsRoute: PlatformSettingsRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface WebsiteRouteChildren {
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteIndexRoute: WebsiteIndexRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof WebsiteRouteWithChildren
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/candidates': typeof PlatformCandidatesRoute
  '/dashboard': typeof PlatformDashboardRoute
  '/jobs': typeof PlatformJobsRouteWithChildren
  '/settings': typeof PlatformSettingsRoute
  '/': typeof WebsiteIndexRoute
  '/jobs/$jobId': typeof PlatformJobsJobIdRoute
}

export interface FileRoutesByTo {
  '': typeof PlatformRouteWithChildren
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/candidates': typeof PlatformCandidatesRoute
  '/dashboard': typeof PlatformDashboardRoute
  '/jobs': typeof PlatformJobsRouteWithChildren
  '/settings': typeof PlatformSettingsRoute
  '/': typeof WebsiteIndexRoute
  '/jobs/$jobId': typeof PlatformJobsJobIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_platform': typeof PlatformRouteWithChildren
  '/_website': typeof WebsiteRouteWithChildren
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_platform/candidates': typeof PlatformCandidatesRoute
  '/_platform/dashboard': typeof PlatformDashboardRoute
  '/_platform/jobs': typeof PlatformJobsRouteWithChildren
  '/_platform/settings': typeof PlatformSettingsRoute
  '/_website/': typeof WebsiteIndexRoute
  '/_platform/jobs/$jobId': typeof PlatformJobsJobIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/todos'
    | '/sign-in'
    | '/sign-up'
    | '/candidates'
    | '/dashboard'
    | '/jobs'
    | '/settings'
    | '/'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/todos'
    | '/sign-in'
    | '/sign-up'
    | '/candidates'
    | '/dashboard'
    | '/jobs'
    | '/settings'
    | '/'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/_auth'
    | '/_platform'
    | '/_website'
    | '/login'
    | '/todos'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_platform/candidates'
    | '/_platform/dashboard'
    | '/_platform/jobs'
    | '/_platform/settings'
    | '/_website/'
    | '/_platform/jobs/$jobId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  WebsiteRoute: typeof WebsiteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TodosRoute: typeof TodosRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  WebsiteRoute: WebsiteRouteWithChildren,
  LoginRoute: LoginRoute,
  TodosRoute: TodosRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_platform",
        "/_website",
        "/login",
        "/todos"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/sign-in",
        "/_auth/sign-up"
      ]
    },
    "/_platform": {
      "filePath": "_platform.tsx",
      "children": [
        "/_platform/candidates",
        "/_platform/dashboard",
        "/_platform/jobs",
        "/_platform/settings"
      ]
    },
    "/_website": {
      "filePath": "_website.tsx",
      "children": [
        "/_website/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/todos": {
      "filePath": "todos.tsx"
    },
    "/_auth/sign-in": {
      "filePath": "_auth/sign-in.tsx",
      "parent": "/_auth"
    },
    "/_auth/sign-up": {
      "filePath": "_auth/sign-up.tsx",
      "parent": "/_auth"
    },
    "/_platform/candidates": {
      "filePath": "_platform/candidates.tsx",
      "parent": "/_platform"
    },
    "/_platform/dashboard": {
      "filePath": "_platform/dashboard.tsx",
      "parent": "/_platform"
    },
    "/_platform/jobs": {
      "filePath": "_platform/jobs.tsx",
      "parent": "/_platform",
      "children": [
        "/_platform/jobs/$jobId"
      ]
    },
    "/_platform/settings": {
      "filePath": "_platform/settings.tsx",
      "parent": "/_platform"
    },
    "/_website/": {
      "filePath": "_website/index.tsx",
      "parent": "/_website"
    },
    "/_platform/jobs/$jobId": {
      "filePath": "_platform/jobs.$jobId.tsx",
      "parent": "/_platform/jobs"
    }
  }
}
ROUTE_MANIFEST_END */
