[project]
name = "uv-fastapi-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.112.1",
    "langchain-mcp-adapters>=0.0.7",
    "langgraph>=0.3.25",
    "pydantic-settings>=2.8.1",
]
