CREATE TABLE "bucket" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bucket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candidates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "candidates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"bucketId" integer NOT NULL,
	"resume_file_name" varchar(256) NOT NULL,
	"resume_aws_key" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
DROP INDEX "name_idx";--> statement-breakpoint
ALTER TABLE "jobs" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "jobs" ALTER COLUMN "description" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "jobs" ALTER COLUMN "updatedAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "jobs" ADD COLUMN "status" text NOT NULL;--> statement-breakpoint
ALTER TABLE "jobs" ADD COLUMN "selectedCandidateId" integer;--> statement-breakpoint
ALTER TABLE "candidates" ADD CONSTRAINT "candidates_bucketId_bucket_id_fk" FOREIGN KEY ("bucketId") REFERENCES "public"."bucket"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bucket_name_idx" ON "bucket" USING btree ("name");--> statement-breakpoint
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_selectedCandidateId_candidates_id_fk" FOREIGN KEY ("selectedCandidateId") REFERENCES "public"."candidates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "job_name_idx" ON "jobs" USING btree ("name");